### ISSUE TITLE
Write tests to debug site

### ISSUE THREAD

**Issue by ghost** [RouteRunner/RouteRunnerApp#59]

**Comment by rjz** [comment]
May or may not be useful for this: [mocha tests for server-side app](https://github.com/rjz/node-express-boilerplate/blob/master/test/spec.js) from an old-ish boilerplate.

If we're planning to dive into client-side tests here, this might be a good time to talk about a build tool, CommonJS modules, and how they can make writing unit tests much easier.

**Comment by leisurgs** [comment]
bugs that need attention, 
1. only a drop down destination works
2. "route it" doesnt work unless there is an origin
3. the "notes section" should have an update on enter, and the clear button needs to give a response when clicked
4. All buttons should give feedback when clicked
5. freezes upon ligin
6. would be nice to use direction on phone when you rout it
